= add a user 
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 24-02-2023


Carry out some first-run sysadmin on the new machine. 

Use the rpi4 CLI.

Use the console to connect.
Use the root account so the console is accessible. 

If you know the IP address, use SSH. 
Use the root account so the private key is accessible. 
This is stored in the .ssh folder on rpi4. 

[source,shell]
----
[root@rpi4 ~]# cat /root/.ssh/id_rsa
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEA0vVjgMBf6tXSqB7fgqiNR0DbHgv3593ogwSv33dzLn3l0gbmc
4f40rzNX1ebAsoBpvnm5bXruhMglvaM5ZbL+LQeUw4os9w6j+IR6qUOla/9lAD8fueP
...
9sEPn/t1mFXSDDpvmLjJfTY47ro449OBLfi3y58lQ75CVnTcF8fhUwv9jPkTzuVRNUm
gGPyNwGbkQp2DelTZJnKYNzpiEfJX/8FYD/4NQLYnzsok82p8lYzlhJWCV41+neUXj0
5YZ0WuDSRBG7CZAAAAGXJvb3RAcnBpNC5sYWIuZXXBsZS5jb20B
-----END OPENSSH PRIVATE KEY-----
[root@rpi4 ~]# 
----

Login with the root account. 
This is the second login, so the /root/.ssh/known_hosts file now contains dev0's key. 

[source,shell]
----
[root@rpi4 ~]# ssh root@192.168.1.234
Web console: https://dev0.home:9090/ or https://192.168.1.139:9090/

Last login: Tue Apr 25 19:53:16 2023 from 192.168.1.201
[root@dev0 ~]# 
----


== add another account 

Check for any home directories. 
None! 

[source,shell]
....
[root@dev0 ~]# ls /home/
[root@dev0 ~]# 
....

Add a user. 
Run these commands.
The guest account can use the same user name as the host user name.

[source,shell]
....
NAME=nick
useradd $NAME
usermod -a -G wheel $NAME
echo 'Password;1' | passwd --stdin $NAME
....


[source,shell]
....
[root@dev0 ~]# NAME=nick
[root@dev0 ~]# useradd $NAME
[root@dev0 ~]# usermod -a -G wheel $NAME
[root@dev0 ~]# echo 'Password;1' | passwd --stdin $NAME
Changing password for user nick.
passwd: all authentication tokens updated successfully.
[root@dev0 ~]# 
....


== connect with SSH

Disconnect from the console. 

Login with the new account. 
I typed the password wrong the first time and got the message  
"There was 1 failed login attempt since the last successful login".

[source,shell]
....
[root@rpi4 ~]# ssh nick@192.168.1.139
nick@192.168.1.139's password: 
Permission denied, please try again.
nick@192.168.1.139's password: 
Web console: https://dev0.home:9090/ or https://192.168.1.139:9090/

Last failed login: Wed Apr 26 15:12:42 BST 2023 from 192.168.1.201 on ssh:notty
There was 1 failed login attempt since the last successful login.
[nick@dev0 ~]$ 
....

Logout

[source,shell]
....
[nick@dev0 ~]$ exit
logout
Connection to 192.168.1.139 closed.
[root@rpi4 ~]# 
....


== stop using root

[source,shell]
....
[root@rpi4 ~]# exit
logout
[nick@rpi4 ~]$ 
....



