= add keys 
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 24-02-2023


Carry out some first-run sysadmin on the new machine. 

Use the rpi4 CLI.

== create a key pair on rpi4 

[nick@rpi4 ~]$ ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/home/nick/.ssh/id_rsa): 
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /home/nick/.ssh/id_rsa
Your public key has been saved in /home/nick/.ssh/id_rsa.pub
The key fingerprint is:
SHA256:abcdefVadheq9vQ4OY7O/XNR/iWack6luQyPigCnO6U nick@rpi4.lab.example.com
The key's randomart image is:
+---[RSA 3072]---+
|          .     |
|       . . .    |
|      + = .     |
|     + * .   .  |
|  . o B S   o.  |
|   +.+ B+  .+o .|
|  .o. .* o ++ o.|
|  E. o= oo*=.  .|
|  .. = +oo*=    |
+----[SHA256]----+
[nick@rpi4 ~]$ 


== use key-based login 

Copy your public key from the host.
This makes login easier and safer. 

Copy the public key.

[source,shell]
....
[nick@rpi4 ~]$ ssh-copy-id nick@192.168.1.139
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/nick/.ssh/id_rsa.pub"
The authenticity of host '192.168.1.139 (192.168.1.139)' can't be established.
ED25519 key fingerprint is SHA256:Qz1mSNCg1oGOilrsGdNishcej5l0VyfH6Porm0MFXFc.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
nick@192.168.1.139's password: 

Number of key(s) added: 1

Now try logging into the machine, with:   "ssh 'nick@192.168.1.139'"
and check to make sure that only the key(s) you wanted were added.

[nick@rpi4 ~]$ 
....

SSH from your workstation to the machine. 

[source,shell]
....
[nick@rpi4 ~]$ ssh nick@192.168.1.139
Web console: https://dev0.home:9090/ or https://192.168.1.139:9090/

Last login: Wed Apr 26 15:12:48 2023 from 192.168.1.201
[nick@dev0 ~]$ 
....


