= use the ip command
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 23-11-2023



[source,shell]
....
[nick@rpi4 ~]$ ip -brief addr show
lo               UNKNOWN        127.0.0.1/8 ::1/128 
eth0             UP             192.168.1.201/24 fdaa:bbcc:ddee:0:dea6:32ff:fed1:32a9/64 2a00:23a8:4b47:fc01:dea6:32ff:fed1:32a9/64 fe80::dea6:32ff:fed1:32a9/64 
wlan0            DOWN           
[nick@rpi4 ~]$ 
....


[source,shell]
....
[nick@rpi4 ~]$ ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether dc:a6:32:d1:32:a9 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.201/24 brd 192.168.1.255 scope global dynamic noprefixroute eth0
       valid_lft 81988sec preferred_lft 81988sec
    inet6 fdaa:bbcc:ddee:0:dea6:32ff:fed1:32a9/64 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 2a00:23a8:4b47:fc01:dea6:32ff:fed1:32a9/64 scope global dynamic noprefixroute 
       valid_lft 62207977sec preferred_lft 31103977sec
    inet6 fe80::dea6:32ff:fed1:32a9/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether e6:10:49:e4:32:fe brd ff:ff:ff:ff:ff:ff permaddr dc:a6:32:d1:32:aa
[nick@rpi4 ~]$ 
....

No bridges 

[source,shell]
....
[nick@rpi4 ~]$ ip -brief link show type bridge
[nick@rpi4 ~]$ 
....

No tunnels


[source,shell]
....
[nick@rpi4 ~]$ ip -brief link show type tun
[nick@rpi4 ~]$ 
....
