= create libvirt network public0
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 23-11-2020


Add network config to libvirt's configuration.
Call the network public0.
The config tells libvirt about bridge _pubbr0_.

== all the networks 

* public network *public0*
* private network *private0* 
* private network *private1* 


== config 

The config tells libvirt about bridge _pubbr0_.
This XML file defines the new network.

[source,XML]
....
<network>
  <name>public0</name>
  <forward mode="bridge"/>
  <bridge name="pubbr0" />
</network>
....

== create the libvirt network public0 

Use the root account.

Change to the libvirt directory. 

Add the XML to a file. 

[source,shell]
....
[root@host1 libvirt]# vi net-public0.xml 
....

Tell libvirt about the new configuration.

[source,shell]
....
[root@host1 libvirt]# virsh net-define net-public0.xml
Network public0defined from net-public0.xml

[root@host1 libvirt]# 
....

Check with the _virsh net-list_ command. 

[source,shell]
....
[root@host1 libvirt]# virsh net-list --all
 Name      State      Autostart   Persistent
----------------------------------------------
 default   active     yes         yes
 public0   inactive   no          yes

[root@host1 libvirt]# 
....


== start the libvirt network

This is a temporary change. 
The network stays active until the machine turns off. 
After the next reboot, this will be inactive again. 

OLD NAMING 

[source,shell]
....
[root@host1 libvirt]# virsh net-start public0
Network public0 started

[root@host1 libvirt]# 
[root@host1 libvirt]# virsh net-list --all
 Name         State    Autostart   Persistent
-----------------------------------------------
 default      active   yes         yes
 public0      active   no          yes

[root@host1 libvirt]# 
....

Make the change permanent. 

[source,shell]
....
[root@host1 libvirt]# virsh net-autostart public0
Network public0 marked as autostarted

[root@host1 libvirt]# 
[root@host1 libvirt]# virsh net-list --all
 Name      State    Autostart   Persistent
--------------------------------------------
 default   active   yes         yes
 public0   active   yes         yes

[root@host1 libvirt]# 
....


=== delete libvirt's public0

If it's not right, remove the new config with _virsh net-undefine_.

[source,shell]
....
[root@host1 libvirt]# virsh net-undefine pubbr0
Network public0 has been undefined

[root@host1 libvirt]# 
....


