= view DNF groups  
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 13-09-2021

A DNF group is a collection of RPM packages. 

Some packages are useful to install together, even though they don't depend on each other to work. 
A DNF group defines a useful collection of packages.

A DNF group is not related to package dependencies. 
Installing one RPM package often means installing more than one package - the one you want and other packages required to make it work. 


== a DNF group 

Fedora has dozens of DNF groups, to help with system administration, office work and container development. 
The https://fedoraproject.org/wiki/Category:SIGs[Fedora SIGs (Special Interest Groups)] often produce their own groups, like the https://fedoraproject.org/wiki/SIGs/3DPrinting[3D Printing] group. 

The DNF group "System Tools" lists packages for working with network connections, interfaces, storage and more. 

Groups are listed under four headings. 

* Available Environment Groups
* Installed Environment Groups
* Installed Groups
* Available Groups


[source,shell]
----
[nick@rpi4 ~]$ dnf group list
Last metadata expiration check: 1:11:13 ago on Mon 17 Apr 2023 07:23:03 BST.
Available Environment Groups:
   Fedora Custom Operating System
   Minimal Install
   Fedora Server Edition
...
Installed Groups:
   Container Management
   Domain Membership
   Headless Management
Available Groups:
   3D Printing
   Administration Tools
   Audio Production
...
[nick@rpi4 ~]$ 
----

The Fedora Server image does not have any installed environment groups. 

== an environment group 

An environment group is everything required to create a customized environment, such as a Fedora Spin.
The Anaconda installer uses environment groups when building a new system.
An environment group contains many groups. 

An environment group contains groups. 

[source,shell]
....
[nick@rpi4 ~]$ dnf group info  'Infrastructure Server'
Last metadata expiration check: 1:18:19 ago on Mon 17 Apr 2023 07:25:27 BST.
Environment Group: Infrastructure Server
 Description: Server for operating network infrastructure services.
 Mandatory Groups:
   Container Management
   Core
   Hardware Support
   Headless Management
   Standard
 Optional Groups:
   Basic Web Server
   DNS Name Server
   Directory Server
   Dogtag Certificate System
   FTP Server
   FreeIPA Server
   Guest Agents
   High Availability
   Load Balancer
   Mail Server
   MariaDB (MySQL) Database
   Network Servers
   PostgreSQL Database
   Printing Support
   Virtualization
   Windows File Server
[nick@rpi4 ~]$ 
....


== a Fedora Spin is an environment group

A https://spins.fedoraproject.org/[Fedora spin] is a themed version of Fedora.
That usually means Fedora combined with one desktop system. 
There are many desktop spins, including the https://spins.fedoraproject.org/en/kde/[KDE Plasma spin], and https://spins.fedoraproject.org/en/kde/[Xfce spin].
A spin can also be Fedora combined with productivity tools.
https://labs.fedoraproject.org/[Fedora Labs] provide an https://labs.fedoraproject.org/en/astronomy/[Astronomy spin], a https://labs.fedoraproject.org/en/games/[Games spin], a https://labs.fedoraproject.org/en/scientific/[Scientific spin] and others. 

A spin is defined using an environment group. 




== group commands 

`dnf group (something)`, where something is info, install, list, remove, upgrade or mark. 
Run `man dnf` and search for _Group Command_. 


== list groups 

List DNF groups. 

[source,shell]
----
[nick@rpi4 ~]$ dnf group list
Last metadata expiration check: 0:05:15 ago on Mon 13 Sep 2021 08:03:53 BST.
Available Environment Groups:
   Fedora Custom Operating System
   Minimal Install
...
   System Tools
   Text-based Internet
   Window Managers
[nick@rpi4 ~]$ 
----


== list hidden groups 

Most groups are hidden. 
A group list shows the most popular 60 groups. 
There are about three times that in total. 

Use the --hidden option. The _Available Environment Groups_ list doesn't change, but the lists of installed and available groups are much longer.

[source,shell]
----
[root@rpi4 ~]# dnf group list --hidden 
Last metadata expiration check: 1:33:10 ago on Mon 17 Apr 2023 07:23:03 BST.
...
Installed Groups:
   ARM Tools
   Container Management
   Core
   Domain Membership
   Guest Agents
   Hardware Support
   Headless Management
   Common NetworkManager Submodules
   Hardware Support for Server Systems
   Fedora Server product core
   Standard
Available Groups:
   3D Printing
   Administration Tools
   Anaconda tools
...
   Xfce Software Development
   XMonad
   XMonad for MATE
[root@rpi4 ~]# 
----


== list packages in a group

List packages in the DNF group "System Tools".

[source,shell]
----
[nick@rpi4 ~]$ dnf group info "System Tools"
Last metadata expiration check: 0:10:21 ago on Mon 13 Sep 2021 08:03:53 BST.
Group: System Tools
 Description: This group is a collection of various tools for the system, such as the client for connecting to SMB shares and tools to monitor network traffic.
 Default Packages:
   BackupPC
   NetworkManager-l2tp
   NetworkManager-libreswan
...
   xdelta
   zisofs-tools
   zsh
 Optional Packages:
   PackageKit-command-not-found
   aide
   aircrack-ng
...
   x3270-x11
   xmobar
   xsel
   zidrav
[nick@rpi4 ~]$ 
----


== lists groups and their IDs 

Each group has a group ID. 
The group name and ID are similar. 
The "Minimal Install" group has ID _minimal-environment_.

[source,shell]
----
[nick@rpi4 ~]$ dnf group list --ids
...
   Minimal Install (minimal-environment)
...
[nick@rpi4 ~]$ 
----

These IDs are also shown with the -v option. 

[source,shell]
----
[nick@rpi4 ~]$ dnf group list -v
Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, groups-manager, needs-restarting, playground, repoclosure, repodiff, repograph, repomanage, reposync
DNF version: 4.8.0
...
updates-modular: using metadata from Wed 15 Sep 2021 19:41:08 BST.
Last metadata expiration check: 0:26:05 ago on Thu 16 Sep 2021 09:54:26 BST.
Available Environment Groups:
   Fedora Custom Operating System (custom-environment)
   Minimal Install (minimal-environment)
   Fedora Workstation (workstation-product-environment)
...
   System Tools (system-tools)
   Text-based Internet (text-internet)
   Window Managers (window-managers)
[nick@rpi4 ~]$ 
----


== install packages in a group using the ID

???

[source,shell]
----
[nick@rpi4 ~]$ sudo dnf install "@system-tools"
...
[nick@rpi4 ~]$ 
----



