= update packages with DNF
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 12-01-2023

Update packages with https://en.wikipedia.org/wiki/DNF_(software)[DNF].

This procedure does not upgrade everything. If you are on an older release of Fedora, like 33, you won't end up with Fedora 34. 
33 is the release number, and changing from one to the next can break things. 
Upgrading the release from Fedora 33 to Fedora 34 is called a system upgrade, and there are a few ways to do it. You can use DNF to https://docs.fedoraproject.org/en-US/quick-docs/upgrading-fedora-online/[upgrade Fedora from one release to the next].


== RPM packages in the installer ISO

Install media don't get updated with the latest packages. 
That includes the ISO file used to install Fedora. 
Packages are frequently updated, so the older the ISO file, the more packages there are to install. 

== update 

[source,shell]
----
[nick@rpi4 ~]$ sudo dnf update
[sudo] password for nick: 
Last metadata expiration check: 0:15:22 ago on Thu 09 Sep 2021 21:24:15 BST.
Dependencies resolved.
================================================================================
 Package                         Arch    Version                  Repo     Size
================================================================================
Installing:
 kernel                          aarch64 5.13.14-100.fc33         updates  74 k
Upgrading:
 NetworkManager                  aarch64 1:1.26.8-1.fc33          updates 2.1 M
...
Installing weak dependencies:
 ntfs-3g-system-compression      aarch64 1.0-7.fc33               updates  28 k
 trousers                        aarch64 0.3.14-4.fc33            updates 146 k

Transaction Summary
================================================================================
Install    9 Packages
Upgrade  362 Packages

Total download size: 477 M
Is this ok [y/N]: 
----



== reboot if the kernel is updated

Reboot to swap from the current kernel to the new one. 

[source,shell]
----
[nick@rpi4 ~]$ sudo systemctl reboot
[sudo] password for nick: 
[nick@rpi4 ~]$ Connection to rpi4 closed by remote host.
Connection to rpi4 closed.
workstation:~ nick$ 
----


