= change the shell prompt
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 11-10-2021

You can play with the prompt layout by changing the PS1 variable. 
The variable contains odd sequences of characters that tell bash what to put where. 

You can also change the color using ANSI escape codes. 
These are more odd-looking character strings that the terminal interprets as special commands. 

The `infocmp` command displays a big list of control sequences, but you won't find these in that list. 

Git users often https://git-scm.com/book/en/v2/Appendix-A%3A-Git-in-Other-Environments-Git-in-Bash[customize the prompt] by running the _git-prompt.sh_ script.


== examine the prompt 

Ever wondered why the prompt looks like this? 

[source,shell]
---- 
[nick@rpi4 ~]$ 
----

A special set of symbols define how the prompt looks. 
A special bash variable named PS1 configures the prompt. 
This isn\t the only PS variable - there are more, numbered from 0 to 4. 
These are described in `man bash`.

[source,shell]
---- 
[nick@rpi4 ~]$ echo $PS1
[\u@\h \W]\$
[nick@rpi4 ~]$ 
----

== special characters 

To play around with the prompt layout, look at the man page (_man bash_) and search for _PROMPTING_. 
It has a big list of backslash-escaped special characters, like the ones used here (\u, \h and \W) .

* \u - user name
* @ - this doesn't get interpreted in any special way. 
* \h - host name (not the domain)
* \W - current directory (not the full path)



== add unicode

Change the layout. This example uses the form $'string' to add the unicode star character (see QUOTING in `man bash`).

[source,shell]
----
PS1=$'\u2605 \u \u2605 \W]\$ '
----

The result looks like this. 

[source,shell]
----
[nick@rpi4 ~]$ PS1=$'\u2605 \u \u2605 \W]\$ '
★ nick ★ ~]$ 
----

Undo your changes. 
Set the PS1 environment variable back to what it was.

[source,shell]
----
PS1='[\u@\h \W]\$ '
----


