site:
  title: Nick's Home Lab, bzzz clunk
  url: https://fedora-on-rpi4.netlify.app
  # start_page default value is OK
  # (https://docs.antora.org/antora/2.3/playbook/site-start-page/)
  # no need to set this site key 
  # (https://docs.antora.org/antora/2.3/playbook/configure-site/#site-key)
  #start_page: fedora-on-rpi4:ROOT:index.adoc
  keys:
    google_analytics: 'G-7K2RCE6KXL'
content:
  sources: 
  - url: https://github.com/nickhardiman/articles-fedora-rpi4.git
    branches: main
ui: 
  bundle:
    url: https://github.com/nickhardiman/antora-ui/raw/master/build/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental_ui
asciidoc:
  attributes:
    experimental: true 
    page-pagination: true 
