= home network
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 13-02-2022


You probably already have a home network with at least two boxes attached to it - a workstation and a router.

A home network is private, with no access from the Internet. 
Getting to the Internet is pretty handy, but unwanted visitors from the Internet are not welcome.

* The workstation is your daily driver. This is usually a laptop running Windows. 

.home network  
....
        +----------------------+
        |                      | 
.-------+-------.      .-------+-------.
|               |      |               |
|  workstation  |      |  router       |-------> Internet  
|               |      |               |  
.---------------.      .---------------.
....

components 

* your workstation. It's https://www.canalys.com/newsroom/global-pc-market-Q4-2021[probably a mobile workstation], such as a notebook or mobile workstation. 
* the ISP's router, your gateway to the Internet
* ethernet cables, if everything isn't wireless.
* other devices. Your home network probably has a lot more than just your workstation and the ISP's router. 
** smart devices. There are probably a whole load of smart devices on this home network, from phone to TV. 
** Network switch 
** WiFi access point. This is probably built into your router. 





