= what you have
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 13-02-2022


You bring the network. 
This is probably a home network with at least two boxes attached to it - a workstation and a router.

A home network is private, with no access from the Internet. 
Getting to the Internet is pretty handy, but unwanted visitors from the Internet are not welcome.

== home network 

You already have a home network with at least two boxes attached to it - a workstation and a router. 

* The workstation is your daily driver. This is usually a laptop running Windows. 

.home network with workstation  
....
        +----------------------+
        |                      | 
.-------+-------.      .-------+-------.
|               |      |               |
|  workstation  |      |  router       |-------> Internet  
|               |      |               |  
.---------------.      .---------------.
....

* the ISP's router, your gateway to the Internet
* your workstation

=== workstation 

The workstation is whatever you work on. 

It's https://www.canalys.com/newsroom/global-pc-market-Q4-2021[probably a mobile workstation], such as a notebook or mobile workstation. 



=== router

The box the ISP gave you. 
This is your gateway to the Internet. 
It's remotely managed by the ISP, not you, so you don't have to touch it.
It's just there and it just works. 


=== other devices 

Your home network probably has a lot more than just your workstation and the ISP's router. 

* smart devices. There are probably a whole load of smart devices on this home network, from phone to TV. 
* Network switch 
* WiFi access point. This is probably built into your router. 
* ethernet cables. 


== a new Raspberry Pi 4 for the home lab 

You probably have the resources to add a new machine to your home network. 
As long as you can figure out how to plug the new Raspberry Pi into the home network, that's  fine. 
A network switch near the new machine makes this easier.

.home network with new Raspberry Pi  
....
        +----------------------+----------------------+
        |                      |                      |
.-------+-------.      .-------+-------.      .-------+-------.
|               |      |               |      |               |
|  Raspberry Pi |      |  workstation  |      | router        |-------> Internet  
|               |      |               |      |               |  
.---------------.      .---------------.      .---------------.
....

