= create libvirt network public0
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 23-11-2020


Add network config to libvirt's configuration.
Call the network *public0*.
The config tells libvirt about bridge _pubbr0_.

== all the networks 

* public network *public0*
* private network *private0* 
* private network *private1* 


== config 

The config tells libvirt about bridge _pubbr0_.
This XML file defines the new network.

[source,XML]
....
<network>
  <name>public0</name>
  <forward mode="bridge"/>
  <bridge name="pubbr0" />
</network>
....

== create the libvirt network public0 

Use the root account.

Change to the libvirt directory. 

[source,shell]
----
[root@rpi4 ~]# cd libvirt/
[root@rpi4 libvirt]# 
----

Add the XML to a file. 

[source,shell]
....
[root@host1 libvirt]# vi net-public0.xml 
....

List all libvirt's networks, both active and inactive. 
There are none. 

[source,shell]
----
[root@rpi4 libvirt]# virsh net-list --all
 Name   State   Autostart   Persistent
----------------------------------------

[root@rpi4 libvirt]#
----

Tell libvirt about the new configuration.
Use the 
https://download.libvirt.org/virshcmdref/html/sect-net-define.html[net-define] 
command. 

[source,shell]
....
[root@rpi4 libvirt]# virsh net-define net-public0.xml
Network public0 defined from net-public0.xml

[root@rpi4 libvirt]#
....

== check your work 

Check with the _virsh net-list_ command. 

[source,shell]
....
[root@rpi4 libvirt]# virsh net-list --all
 Name      State      Autostart   Persistent
----------------------------------------------
 public0   inactive   no          yes

[root@rpi4 libvirt]# 
....

Behind the scenes, systemd starts some virt processes to do the work. 
These disappear after two minutes. 

[source,shell]
....
[root@rpi4 libvirt]# ps x | grep virt
  11382 ?        Ssl    0:00 /usr/sbin/virtqemud --timeout 120
  11403 ?        Ssl    0:00 /usr/sbin/virtnetworkd --timeout 120
  11518 pts/0    S+     0:00 grep --color=auto virt
[root@rpi4 libvirt]# 
....


== start the libvirt network

The bridge is already in use, but libvirt's virtual network is not.
Manually start it. 

This is a temporary change - the network is transient. 
The network stays active until the machine turns off. 
After the next reboot, this will be inactive again. 

[source,shell]
....
[root@rpi4 libvirt]# virsh net-start public0
Network public0 started

[root@rpi4 libvirt]# 
[root@rpi4 libvirt]# virsh net-list --all
 Name      State    Autostart   Persistent
--------------------------------------------
 public0   active   no          yes

[root@rpi4 libvirt]# 
....

Make the change permanent.
Enable automatic starting with the 
https://download.libvirt.org/virshcmdref/html/sect-net-autostart.html[net-autostart] 
command. 

[source,shell]
....
[root@rpi4 libvirt]# virsh net-autostart public0
Network public0 marked as autostarted

[root@rpi4 libvirt]# 
[root@rpi4 libvirt]# virsh net-list --all
 Name      State    Autostart   Persistent
--------------------------------------------
 public0   active   yes         yes

[root@rpi4 libvirt]# 
....


=== problems? delete libvirt's public0

If it's not right, remove the new config with _virsh net-undefine_.

[source,shell]
....
[root@rpi4 libvirt]# virsh net-destroy public0
Network public0 destroyed

[root@rpi4 libvirt]#
[root@rpi4 libvirt]# virsh net-undefine public0
Network public0 has been undefined

[root@rpi4 libvirt]# 
[root@rpi4 libvirt]# virsh net-list --all
 Name   State   Autostart   Persistent
----------------------------------------

[root@rpi4 libvirt]# 
....


