= create network private0
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 23-11-2020


Add network config to libvirt's configuration.
Call the network *private0*.
The config tells libvirt about bridge _privbr0_.

== all the networks 

* public network *public0*
* private network *private0* 
* private network *private1* 


== config 

The config tells libvirt about bridge _privbr0_.
This XML file defines the new network.

[source,XML]
....
<network>
  <name>private0</name>
  <forward mode="bridge"/>
  <bridge name="privbr0" />
</network>
....

== create the libvirt network public0 

Use the root account.

Change to the libvirt directory. 

[source,shell]
----
[root@rpi4 ~]# cd libvirt/
[root@rpi4 libvirt]# 
----

Add the XML to a file. 

[source,shell]
....
[root@host1 libvirt]# vi net-private0.xml 
....

List all libvirt's networks, both active and inactive. 
There are none. 

[source,shell]
----
[root@rpi4 libvirt]# virsh net-list --all
 Name   State   Autostart   Persistent
----------------------------------------
 public0   active   yes         yes

[root@rpi4 libvirt]#
----

Tell libvirt about the new configuration.
Use the 
https://download.libvirt.org/virshcmdref/html/sect-net-define.html[net-define] 
command. 

[source,shell]
....
[root@rpi4 libvirt]#  virsh net-define net-private0.xml
Network private0 defined from net-private0.xml

[root@rpi4 libvirt]# 
....

== check your work 

Check with the _virsh net-list_ command. 

[source,shell]
....
[root@rpi4 libvirt]# virsh net-list --all
 Name       State      Autostart   Persistent
-----------------------------------------------
 private0   inactive   no          yes
 public0    active     yes         yes

[root@rpi4 libvirt]# 
....



== start the libvirt network

The bridge is already in use, but libvirt's virtual network is not.
Manually start it. 

This is a temporary change - the network is transient. 
The network stays active until the machine turns off. 
After the next reboot, this will be inactive again. 

[source,shell]
....
[root@rpi4 libvirt]# virsh net-start private0
Network private0 started

[root@rpi4 libvirt]# 
....

Make the change permanent.
Enable automatic starting with the 
https://download.libvirt.org/virshcmdref/html/sect-net-autostart.html[net-autostart] 
command. 

[source,shell]
....
[root@rpi4 libvirt]# virsh net-autostart private0
Network private0 marked as autostarted

[root@rpi4 libvirt]# 
....

Check. 

[source,shell]
....
[root@rpi4 libvirt]# virsh net-list --all
 Name       State    Autostart   Persistent
---------------------------------------------
 private0   active   yes         yes
 public0    active   yes         yes

[root@rpi4 libvirt]# 
....


== store create commands in a script

The commands have already been run, but there is no record of what was done. 

Store the commands to create this libvirt network in a file. 

[source,shell]
----
[root@rpi4 ~]# cd libvirt/
[root@rpi4 libvirt]# 
[root@rpi4 libvirt]# touch net-private0-add.sh
[root@rpi4 libvirt]# chmod 754 net-private0-add.sh
[root@rpi4 libvirt]# vim net-private0-add.sh
----

Add this content. 

[source,bash]
....
echo before -----------------------
virsh net-list --all
echo add -----------------------
virsh net-define net-private0.xml
virsh net-start private0
virsh net-autostart private0
echo after -----------------------
virsh net-list --all
....



=== problems? delete libvirt's private0

If it's not right, remove the new config with _virsh net-undefine_.

net-destroy changes state from active to inactive. 
net-undefine removes config. 

[source,shell]
....
[root@rpi4 libvirt]# virsh net-destroy private0
Network private0 destroyed

[root@rpi4 libvirt]#
[root@rpi4 libvirt]# virsh net-undefine private0
Network private0 has been undefined

[root@rpi4 libvirt]# 
[root@rpi4 libvirt]# virsh net-list --all
 Name   State   Autostart   Persistent
----------------------------------------

[root@rpi4 libvirt]# 
....


== store delete commands in a script

Store the commands to delete this bridge in a file. 

[source,shell]
----
[root@rpi4 ~]# cd libvirt/
[root@rpi4 libvirt]# 
[root@rpi4 libvirt]# touch net-private0-delete.sh
[root@rpi4 libvirt]# chmod 754 net-private0-delete.sh
[root@rpi4 libvirt]# vim net-private0-delete.sh
----

Add this content. 

[source,bash]
....
echo before -----------------------
virsh net-list --all
echo delete -----------------------
virsh net-destroy private0
virsh net-undefine private0
echo after -----------------------
virsh net-list --all
....
