= simple - configure
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 15-04-2023

!!! host name rpi4 is being picked up from DHCP. Should be localhost?

The Fedora server image does not come with any passwords or user accounts. 
First run throws up a menu of basic options to configure. 

== initial-setup

A setup agent called 
https://github.com/rhinstaller/initial-setup[initial-setup] 
manages this first-run configuration. 

When the system is up and running, use the rpm command to query its database (-q) to get information on this package (-i).

[source,shell]
----
[root@rpi4 ~]# rpm -qi initial-setup
Name        : initial-setup
...
Description :
The initial-setup utility runs after installation.  It guides the user through
a series of steps that allows for easier configuration of the machine.
[root@rpi4 ~]# 
----

== anaconda spokes 

Anaconda is a complicated installer that uses what it calls a 
https://rhinstaller.github.io/anaconda-addon-development-guide/sect-anaconda-hub-and-spoke.html[hub and spoke model]. 
It's a modular architecture that  Anaconda sysadmins and developers have to know, and absolutely nobody else is interested in. 
The menu options that appear when first booting the Fedora Server image come from spokes. 
Sometimes these menu options are referred to as anaconda spokes.

[source,shell]
----
===========================================================================
===========================================================================

1) [x] Language settings           2) [x] Time settings
       (English (United States))          (US/Eastern timezone)
3) [x] Network configuration       4) [x] Root password
       (Wired (eth0) connected)           (Root account is disabled)
5) [ ] User creation
       (No user will be created)

Please make a selection from the above ['c' to continue, 'q' to quit, 'r' to refresh]:
----

Entering 'c' for continue without making any changes is a bad idea. 
There will be no way of logging in. 

Typing a number and hitting return shows another menu of choices. 
For instance, the language sub-menu of this main menu has 69 choices. 
The English sub-sub-menu has no less than 18 English variants, from Australia to Zimbabwe.


== answer anaconda's questions

Typing a number shows another menu of choices. 
For instance, the language sub-menu of this main menu has 69 choices. 
The English sub-sub-menu has no less than 18 English variants, from Australia to Zimbabwe.

* If, like most of the world, you don't live in eastern USA, change language and time settings.
* Set up the root account and another admin account. This password is based on dictionary words, which is usually a bad idea. At this stage, insecure passwords are fine. 
** root password: redhat
** user name: nick
** user password: redhat
** user is an administrator: yes

This config process only takes a minute.
No packages are downloaded or installed. 
Then the login prompt appears, along with a few lines of information.

[source,shell]
----
Fedora Linux 37 (Server Edition)
Kernel 6.0.7-301.fc37.aarch64 on an aarch64 (tty1)

Web console: https://rpi4:9090/ or https://192.168.1.2:9090/

rpi4 login:
----

== /root/initial-setup-ks.cfg

Anaconda stores these settings in file /root/initial-setup-ks.cfg, along with many other settings.

[source,shell]
----
[root@rpi4 ~]# cat initial-setup-ks.cfg 
# Generated by pykickstart v3.41
#version=DEVEL
# Use text mode install
text
# Run the Setup Agent on first boot
firstboot --reconfig
...
----
