= boot the raw server image   
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 28-02-2023

xref:introduction:layer-diagram.adoc[layers]

* guest application 
* guest container
* guest OS  
* guest hardware
* host hypervisor
* host OS      <- here
* host firmware
* host hardware

The easiest way to get up and running with Fedora. 

Simple install. You get what you're given (U-Boot firmware, no desktop, etc.)

* xref:drive-raw-image.adoc[]

Complex install with choices (Tiano Core firmware, full installer, etc.)

* xref:drive-uefi.adoc[]
* xref:drive-os-installer.adoc[]
* xref:os-install.adoc[]


Fedora Server includes about 1GB of swap, a simple LVM configuration and 1000 packages. 
Fedora Server does not include a graphical desktop. 


== get the ISO file

https://getfedora.org/en/server/download/

== prepare the USB drive 

Unpack 

[source,shell]
----
[root@host1 images]# unxz Fedora-Server-37-1.7.aarch64.raw.xz 
[root@host1 images]# 
----

Copy image

[source,shell]
----
[root@host1 images]# dd if=Fedora-Server-37-1.7.aarch64.raw of=/dev/sdb bs=1M
7168+0 records in
7168+0 records out
7516192768 bytes (7.5 GB, 7.0 GiB) copied, 447.263 s, 16.8 MB/s
[root@host1 images]# 
----

turn off Pi

Sync and remove SD card 

[source,shell]
----
[root@host1 images]# eject /dev/sdb
[root@host1 images]# 
----

insert USB drive

== first boot

turn on Pi

Answer text-based anaconda questions. 

DNF 3 is too big for a 1GB Raspberry Pi. 
Install microdnf. 

[source,shell]
----
sudo -i
dnf install microdnf
----

Update hundreds of packages.

[source,shell]
----
microdnf update
----

Turn off.

[source,shell]
----
systemctl poweroff
----
