= simple - boot the raw server image   
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 28-02-2023

xref:introduction:layer-diagram.adoc[layers]

* guest application 
* guest container
* guest OS  
* guest hardware
* host hypervisor
* host OS      <- here
* host firmware
* host hardware

The easiest way to get up and running with Fedora. 

Simple install. You get what you're given (U-Boot firmware, no desktop, etc.)

* xref:drive-raw-image.adoc[]

Complex install with choices (Tiano Core firmware, full installer, etc.)

* xref:drive-uefi.adoc[]
* xref:drive-os-installer.adoc[]
* xref:os-install.adoc[]


== power up 

Insert both USB drives. 

Plug in

Turn on.

== the console 

The keyboard, mouse and display screen attached to the Pi form the console. 
This is a special administration terminal.
The console name is a leftover from long ago, when a computer console was like a table console: a small table with a workstation on it. 
Now, a console is a text-based terminal that gets special treatment by the OS. 
Fedora also comes with a web-based console named Cockpit. 

A succession of screens show U-Boot, GRUB, OS, then the Anaconda interactive text mode menu.

[source,shell]
----
Booting Fedora Linux (6.0.7-301.fc37.aarch64) 37 (Server Edition) 
----

No changes have been made yet. 
The machine can be powered off and on without causing any harm.

== interactive text mode 

[source,shell]
----
===========================================================================
===========================================================================

1) [x] Language settings           2) [x] Time settings
       (English (United States))          (US/Eastern timezone)
3) [x] Network configuration       4) [x] Root password
       (Wired (eth0) connected)           (Root account is disabled)
5) [ ] User creation
       (No user will be created)

Please make a selection from the above ['c' to continue, 'q' to quit, 'r' to refresh]:
----

Anaconda starts in 
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/installation_guide/sect-installation-text-mode-s390[text mode] and interactive mode. 
A text menu with no hint of graphics or color appears, asks questions and waits for answers. 
Organizations prefer non-interactive mode, because the sysadmin installing a hundred machines using interactive mode would lose the will to live. 
For one machine, interactive mode is fine. 

Being interactive does mean you need to attach a keyboard. 



