= complex - install the Fedora OS
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 24-10-2020

Initial configuration of the OS takes a few minutes – a couple minutes waiting for boot-up, and a couple to fill out the spokes of anaconda’s text-based installer. 
Write down your root and user passwords somewhere safe. 

== power up 

Insert both USB drives. 

Plug in

turn on

wait for anaconda 

== configure 

I set mine up with a user named _nick_ who is an administrator (a member of the _wheel_ group). 

After setup, the login prompt appears.  
Log in with the _root_ account. 
The prompt shows the host name is set to _localhost_. 

[source,shell]
----
[root@localhost ~]# 
----

Congratulations! Your Fedora Pi is up and operational.

== check your work 

Power down the Pi, then power it back up again. 

Power down. 

* Power down with `systemctl poweroff`.
* Wait a few seconds. The screen goes dark and the activity LED on the board stops flashing.
* Switch off the power. 

Power up. 

* Switch on the power. 
* Wait a few seconds. Bootloader messages briefly appear, followed by the login prompt. 
* Log in with the root account. 


