= update packages with DNF
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 12-01-2021

Update packages with https://en.wikipedia.org/wiki/DNF_(software)[DNF].

This procedure does not upgrade everything. If you are on an older release of Fedora, like 33, you won't end up with Fedora 34. 
33 is the release number, and changing from one to the next can break things. 
Upgrading the release from Fedora 33 to Fedora 34 is called a system upgrade, and there are a few ways to do it. You can use DNF to https://docs.fedoraproject.org/en-US/quick-docs/upgrading-fedora-online/[upgrade Fedora from one release to the next].

For more information on DNF, see

* The https://dnf.readthedocs.io/en/latest/index.html[DNF user guide] 
* https://docs.fedoraproject.org/en-US/fedora/f34/system-administrators-guide/package-management/DNF/[Fedora docs]
8 https://fedoraproject.org/wiki/DNF[Fedora wiki]
* The DNF command reference page, by running `man dnf`. This page only makes sense for experienced users.

== the dnf command 

DNF packages are already installed. 
There's the dnf package which provides dnf itself, dnf-plugins-core which extends what dnf can do, python3-dnf which fills up /usr/lib/python3.6/site-packages/dnf/, and others.   

These packages provide DNF version 4. 

[source,shell]
----
[nick@rpi4 ~]$ dnf --version
4.6.1
  Installed: dnf-0:4.6.1-1.fc33.noarch at Thu 15 Apr 2021 13:09:56 GMT
  Built    : Fedora Project at Tue 02 Mar 2021 16:03:22 GMT

  Installed: rpm-0:4.16.1.3-1.fc33.aarch64 at Thu 15 Apr 2021 13:06:45 GMT
  Built    : Fedora Project at Mon 22 Mar 2021 11:27:48 GMT
[nick@rpi4 ~]$ 
----



== view advisories

Fedora calls package updates _advisories_. There are three types: security, bug fix and enhancement.

* A security advisory package fixes security problems. A security package also has a priority of low, moderate, important and critical.  
* A bugfix advisory package fixes code problems. 
* An enhancement advisory package provides new features. 

If software hasn't been updated for a while, there can be a lot of these. 
DNF can print totals for each type. 

[source,shell]
----
[nick@rpi4 ~]$ dnf updateinfo --summary
Last metadata expiration check: 0:07:28 ago on Thu 09 Sep 2021 21:20:33 BST.
Updates Information Summary: available
    38 Security notice(s)
         1 Critical Security notice(s)
        12 Important Security notice(s)
        15 Moderate Security notice(s)
         8 Low Security notice(s)
    69 Bugfix notice(s)
    23 Enhancement notice(s)
    23 other notice(s)
[nick@rpi4 ~]$ 
----

Use DNF to list all these packages. 

[source,shell]
----
[nick@rpi4 ~]$ dnf updateinfo --list
...
[nick@rpi4 ~]$ dnf updateinfo --list
FEDORA-2021-8a91778c77 unknown        NetworkManager-1:1.26.8-1.fc33.aarch64
FEDORA-2021-8a91778c77 unknown        NetworkManager-adsl-1:1.26.8-1.fc33.aarch64
...
FEDORA-2021-0f36063660 enhancement    appstream-data-33-3.fc33.noarch
FEDORA-2021-8d0e5b3cd8 Moderate/Sec.  apr-1.7.0-7.fc33.aarch64
...
FEDORA-2021-312568e814 bugfix         yum-4.8.0-1.fc33.noarch
FEDORA-2021-61a7c105e3 bugfix         zchunk-libs-1.1.15-1.fc33.aarch64
[nick@rpi4 ~]$ 
----



== a repository

Packages are downloaded from repositories. 

[source,shell]
----
[nick@rpi4 ~]$ dnf repolist
repo id                       repo name
fedora                        Fedora 33 - aarch64
fedora-cisco-openh264         Fedora 33 openh264 (From Cisco) - aarch64
fedora-modular                Fedora Modular 33 - aarch64
updates                       Fedora 33 - aarch64 - Updates
updates-modular               Fedora Modular 33 - aarch64 - Updates
[nick@rpi4 ~]$ 
----

These are defined in the configuration directory /etc/yum.repos.d/.


== update 

[source,shell]
----
[nick@rpi4 ~]$ sudo dnf update
[sudo] password for nick: 
Last metadata expiration check: 0:15:22 ago on Thu 09 Sep 2021 21:24:15 BST.
Dependencies resolved.
================================================================================
 Package                         Arch    Version                  Repo     Size
================================================================================
Installing:
 kernel                          aarch64 5.13.14-100.fc33         updates  74 k
Upgrading:
 NetworkManager                  aarch64 1:1.26.8-1.fc33          updates 2.1 M
...
Installing weak dependencies:
 ntfs-3g-system-compression      aarch64 1.0-7.fc33               updates  28 k
 trousers                        aarch64 0.3.14-4.fc33            updates 146 k

Transaction Summary
================================================================================
Install    9 Packages
Upgrade  362 Packages

Total download size: 477 M
Is this ok [y/N]: 
----

Install media don't get updated with the latest packages. 
That includes the ISO file used to install Fedora. 
Packages are frequently updated, so the older the ISO file, the more packages there are to install. 


== reboot if the kernel is updated

Reboot to swap from the current kernel to the new one. 

[source,shell]
----
[nick@rpi4 ~]$ sudo systemctl reboot
[sudo] password for nick: 
[nick@rpi4 ~]$ Connection to rpi4 closed by remote host.
Connection to rpi4 closed.
workstation:~ nick$ 
----


