= use the vim editor
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 25-01-2021

Vi was written way back in the 1970s, and has been improved, copied and used by sysadmins ever since. 

One popular copy is https://en.wikipedia.org/wiki/Vim_(text_editor)[vim]. 
https://www.vim.org/[vim] home. 
Installing the vim package replaces vi.
https://vimawesome.com/[Many vim plugins] are available, to help with syntax checking, color scheme, code snippets, and so on. 

Vim was copied and updated to create https://neovim.io/[neovim].


== learn vim 

* book https://www.apress.com/gp/book/9781484202517[Pro Vim]
* wiki https://vim.fandom.com/wiki/Vim_Tips_Wiki
* vim help files https://vimhelp.org/

== install vim

[source,shell]
----
[nick@host1 ~]$ sudo dnf install vim
[sudo] password for nick: 
Updating Subscription Management repositories.
Last metadata expiration check: 2:00:42 ago on Mon 25 Jan 2021 08:07:53 GMT.
Dependencies resolved.
====================================================================================================================================
 Package                     Architecture        Version                        Repository                                     Size
====================================================================================================================================
Installing:
 vim-enhanced                x86_64              2:8.0.1763-15.el8              rhel-8-for-x86_64-appstream-rpms              1.4 M
Installing dependencies:
 gpm-libs                    x86_64              1.20.7-15.el8                  rhel-8-for-x86_64-appstream-rpms               39 k
 vim-common                  x86_64              2:8.0.1763-15.el8              rhel-8-for-x86_64-appstream-rpms              6.3 M
 vim-filesystem              noarch              2:8.0.1763-15.el8              rhel-8-for-x86_64-appstream-rpms               48 k

Transaction Summary
====================================================================================================================================
Install  4 Packages

Total download size: 7.8 M
Installed size: 30 M
Is this ok [y/N]: 
----

== changes

If you run the vi command, you now get vim instead. 

[source,shell]
----
[nick@host1 ~]$ which vi
alias vi='vim'
	/usr/bin/vim
[nick@host1 ~]$ 
----

Viminfo stores state information, like command history and file marks. 

[source,shell]
----
[nick@host1 ~]$ cat .viminfo 
# This viminfo file was generated by Vim 8.0.
# You may edit it if you are careful!
...
----

== configuration 

/etc/vimrc

This file contains a few terminal control commands. 
A terminal comes with many commands for highlighting text, erasing it, moving the cursor and so on. 

The _/etc/vimrc_ file contains text formatting instructions for the terminal, like these. 

[source,bash]
----
if &term=="xterm"
     set t_Co=8
     set t_Sb=^[[4%dm
     set t_Sf=^[[3%dm
endif
----

Display the file content. 
Listing the _/etc/vimrc_ file leads to some odd terminal behaviour if these commands are executed, rather than printed. 
Avoid this with -v (show nonprinting characters). 

[source,shell]
----
[nick@host1 ~]$ cat -v /etc/vimrc 
if v:lang =~ "utf8$" || v:lang =~ "UTF-8$"
   set fileencodings=ucs-bom,utf-8,latin1
endif
...
" Don't wake up system with blinking cursor:
" http://www.linuxpowertop.org/known.php
let &guicursor = &guicursor . ",a:blinkon0"
[nick@host1 ~]$ 
----


== use 

syntax highlighting 

[source,shell]
----
----



copy and paste 

[source,shell]
----
----



cursor column  

[source,shell]
----
----


