= application
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 14-02-2022

The top layer of the technical stack is the business end of computers. It's the layer where work is done for users, rather than work to make the computer go.  

Most of the work of the lower layers is hidden from applications. An editor needs to know how to ask the OS to store a file, but it doesn't need to know how that file is split into blocks on a storage volume. 

* guest application  <-- here
* guest container
* guest OS 
* guest hardware 
* host hypervisor <-- the hypervisor is also an application
* host OS 
* host firmware
* host hardware 




== binary incompatibility

An application can't run on any computer running the same OS. A binary executable can't be shifted from an X86-64 computer to an AARCH64 computer. Those two CPUs talk different hardware languages, and the OS doesn't hide those differences. The OS does filter out some firmware and hardware details to make the application programmer's job easier, but does not hide everything.

This binary incompatibility problem has been biting application programmers forever. Solutions are all complicated.  

* emulate one type of hardware while running on another (like qemu and bochs)
* add a new runtime environment and run your code in that (like JVM and MoarVM)
* add an entire virtual machine, install an OS and run your code in that (like KVM and VMware)
* abandon the binary distribution idea and make users compilee everything from source code

== this application layer is not the famous network application layer

This application layer is a little different from the top layer of the OSI model (layer 7) and the top layer of the TCP/IP model (layer 4). These are networking models that separate the different types of communication needed in a network. The top layers of these models describe the protocols and interfaces required for applications to communicate. A web server needs to know how to talk HTTP, but it doesn't need to know how to split an HTTP conversation into packets and send them across the network. 

=== TCP/IP layers 

* 4. Application 
* 3. Transport 
* 2. Internet
* 1. Link 

=== OSI model layers

* 7. Application
* 6. Presentation
* 5. Session
* 4. Transport
* 3. Network
* 2. Data Link
* 1. Physical
